<a href="https://colab.research.google.com/github/erickunix/slm/blob/main/Competationreal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
import sklearn

In [39]:
import seaborn as sn
import matplotlib.pyplot as plt

In [40]:
df = pd.read_csv('/content/SLM_S2021/Competition/hotels_train.csv')
df

              hotel  ...  total_of_special_requests
0      Resort Hotel  ...                          0
1      Resort Hotel  ...                          0
2      Resort Hotel  ...                          0
3      Resort Hotel  ...                          0
4      Resort Hotel  ...                          1
...             ...  ...                        ...
59995    City Hotel  ...                          0
59996    City Hotel  ...                          0
59997    City Hotel  ...                          1
59998    City Hotel  ...                          0
59999    City Hotel  ...                          1

[60000 rows x 27 columns]

In [41]:
df.describe()

        is_canceled  ...  total_of_special_requests
count  60000.000000  ...               60000.000000
mean       0.422033  ...                   0.509117
std        0.493888  ...                   0.767502
min        0.000000  ...                   0.000000
25%        0.000000  ...                   0.000000
50%        0.000000  ...                   0.000000
75%        1.000000  ...                   1.000000
max        1.000000  ...                   5.000000

[8 rows x 18 columns]

In [42]:
df.head()

          hotel  ...  total_of_special_requests
0  Resort Hotel  ...                          0
1  Resort Hotel  ...                          0
2  Resort Hotel  ...                          0
3  Resort Hotel  ...                          0
4  Resort Hotel  ...                          1

[5 rows x 27 columns]

In [43]:
df = df.replace({"Resort Hotel": 0, "City Hotel":1})

In [44]:
df['market_segment'].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Aviation'], dtype=object)

In [45]:
df['market_segment'] = df['market_segment'].replace({'Direct': 0, 'Corporate': 1, 'Online TA':2, 'Offline TA/TO':3,
       'Complementary':4, 'Groups':5, 'Aviation':6})

In [46]:
df['arrival_date_month'] = df['arrival_date_month'].replace({'January': 1, 'February': 2,'March': 3,'April': 4,'May': 5,'June': 6,'July': 7,'August': 8,
            'September': 9, 
            'October': 10,
            'November': 11, 'December': 12 })

In [47]:
df['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [48]:
df['distribution_channel'] = df['distribution_channel'].replace({'Direct':0, 'Corporate':1, 'TA/TO':2, 'Undefined':3, 'GDS':4})

In [49]:
df['meal'] = df['meal'].replace({'BB': 1, 'HB': 2,'SC': 3,'Undefined': 4,'FB': 5})

In [50]:
df['deposit_type'].unique()

array(['No Deposit', 'Refundable', 'Non Refund'], dtype=object)

In [51]:
df['deposit_type'] = df['deposit_type'].replace({'No Deposit':0, 'Refundable':1, 'Non Refund':2})

In [52]:
df['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [53]:
df['customer_type'] = df['customer_type'].replace({'Transient':0, 'Contract':1, 'Transient-Party':2, 'Group':3})

In [54]:
df['reserved_room_type'] = df['reserved_room_type'].replace({'A': 1, 'B': 2,'C': 3,'D': 4,'E': 5,'F': 6,'G': 7,'H': 8,
            'L': 9, 
            'P': 10 })

In [55]:
df['assigned_room_type'] = df['assigned_room_type'].replace({ 'A' : 1 , 'D' : 2, 'E' : 3, 'C' : 4, 'F':5, 'G':6, 'B':7, 'H':8, 'I': 9, 'K':10, 'P':11, 'L':12})

In [56]:
corr_matrix = df.corr()

In [57]:
corr_matrix[corr_matrix>0.5]

#arrival_date_week_number- high positive correlation
#stays_in_weekend nights - high positive correlation

                                hotel  ...  total_of_special_requests
hotel                             1.0  ...                        NaN
is_canceled                       NaN  ...                        NaN
lead_time                         NaN  ...                        NaN
arrival_date_year                 NaN  ...                        NaN
arrival_date_month                NaN  ...                        NaN
arrival_date_week_number          NaN  ...                        NaN
arrival_date_day_of_month         NaN  ...                        NaN
stays_in_weekend_nights           NaN  ...                        NaN
stays_in_week_nights              NaN  ...                        NaN
adults                            NaN  ...                        NaN
children                          NaN  ...                        NaN
babies                            NaN  ...                        NaN
meal                              NaN  ...                        NaN
market_segment                    NaN  ...                        NaN
distribution_channel              NaN  ...                        NaN
is_repeated_guest                 NaN  ...                        NaN
previous_cancellations            NaN  ...                        NaN
previous_bookings_not_canceled    NaN  ...                        NaN
reserved_room_type                NaN  ...                        NaN
assigned_room_type                NaN  ...                        NaN
booking_changes                   NaN  ...                        NaN
deposit_type                      NaN  ...                        NaN
days_in_waiting_list              NaN  ...                        NaN
customer_type                     NaN  ...                        NaN
adr                               NaN  ...                        NaN
required_car_parking_spaces       NaN  ...                        NaN
total_of_special_requests         NaN  ...                        1.0

[27 rows x 27 columns]

In [58]:
corr_matrix[corr_matrix<-0.5]

#arrival_date_week_number, arrival_date_week_number (kind of same thing, maybe to drop one of them) - high negative correlation

                                hotel  ...  total_of_special_requests
hotel                             NaN  ...                        NaN
is_canceled                       NaN  ...                        NaN
lead_time                         NaN  ...                        NaN
arrival_date_year                 NaN  ...                        NaN
arrival_date_month                NaN  ...                        NaN
arrival_date_week_number          NaN  ...                        NaN
arrival_date_day_of_month         NaN  ...                        NaN
stays_in_weekend_nights           NaN  ...                        NaN
stays_in_week_nights              NaN  ...                        NaN
adults                            NaN  ...                        NaN
children                          NaN  ...                        NaN
babies                            NaN  ...                        NaN
meal                              NaN  ...                        NaN
market_segment                    NaN  ...                        NaN
distribution_channel              NaN  ...                        NaN
is_repeated_guest                 NaN  ...                        NaN
previous_cancellations            NaN  ...                        NaN
previous_bookings_not_canceled    NaN  ...                        NaN
reserved_room_type                NaN  ...                        NaN
assigned_room_type                NaN  ...                        NaN
booking_changes                   NaN  ...                        NaN
deposit_type                      NaN  ...                        NaN
days_in_waiting_list              NaN  ...                        NaN
customer_type                     NaN  ...                        NaN
adr                               NaN  ...                        NaN
required_car_parking_spaces       NaN  ...                        NaN
total_of_special_requests         NaN  ...                        NaN

[27 rows x 27 columns]

In [59]:
y = df['is_canceled']
x = df.drop(['is_canceled'], axis=1)

In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [61]:
from sklearn.linear_model import LogisticRegression

In [62]:
clf = LogisticRegression(random_state=0).fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

In [63]:
clf.score(x_test, y_test)

0.7716666666666666

In [64]:
clf.score(x_train, y_train)

0.773